package com.work.domain;

// Generated 2014-10-10 0:01:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TBusinessDirectory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_BUSINESS_DIRECTORY")
public class BusinessDirectory implements java.io.Serializable {

	private String id;
	private String contacts;
	private String contactPhone;
	private String noteName;
	private String remarks;
	private String provinceName;
	private String cityName;
	private String address;
	private Integer status;
	private String imagePath;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;

	public BusinessDirectory() {
	}

	public BusinessDirectory(String id) {
		this.id = id;
	}

	public BusinessDirectory(String id, String contacts, String contactPhone, String noteName, String remarks,
			String provinceName, String cityName, String address, Integer status, String imagePath, String creator,
			Date createDate, String modifier, Date modifyDate) {
		this.id = id;
		this.contacts = contacts;
		this.contactPhone = contactPhone;
		this.noteName = noteName;
		this.remarks = remarks;
		this.provinceName = provinceName;
		this.cityName = cityName;
		this.address = address;
		this.status = status;
		this.imagePath = imagePath;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CONTACTS", length = 50)
	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	@Column(name = "CONTACT_PHONE", length = 20)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "NOTE_NAME", length = 50)
	public String getNoteName() {
		return this.noteName;
	}

	public void setNoteName(String noteName) {
		this.noteName = noteName;
	}

	@Column(name = "REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "PROVINCE_NAME", length = 500)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "CITY_NAME", length = 500)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "ADDRESS", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "IMAGE_PATH", length = 500)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "CREATOR", length = 20, updatable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19, updatable = false)
	public Date getCreateDate() {
		return this.createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
}
