package com.work.domain;

// Generated 2014-9-22 15:38:19 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TCommentInfo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_COMMENT_INFO")
public class CommentInfo implements java.io.Serializable {

	private String commentId;
	private String userIp;
	private MemberInfo member;
	private String infoId;
	private String content;
	private String title;
	private Integer infoType;
	private Long floorNum;
	private Integer proStatus;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;

	public CommentInfo() {
	}

	public CommentInfo(String commentId) {
		this.commentId = commentId;
	}

	public CommentInfo(String commentId, String userIp, String memberId, String infoId, String content, String title,
			Integer infoType, Long floorNum, Integer proStatus, String creator, Date createDate, String modifier,
			Date modifyDate) {
		this.commentId = commentId;
		this.userIp = userIp;
		this.infoId = infoId;
		this.content = content;
		this.title = title;
		this.infoType = infoType;
		this.floorNum = floorNum;
		this.proStatus = proStatus;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "COMMENT_ID", unique = true, nullable = false, length = 32)
	public String getCommentId() {
		return this.commentId;
	}

	public void setCommentId(String commentId) {
		this.commentId = commentId;
	}

	@Column(name = "USER_IP", length = 32)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "INFO_ID", length = 32)
	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	@Column(name = "CONTENT", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "INFO_TYPE")
	public Integer getInfoType() {
		return this.infoType;
	}

	public void setInfoType(Integer infoType) {
		this.infoType = infoType;
	}

	@Column(name = "FLOOR_NUM")
	public Long getFloorNum() {
		return this.floorNum;
	}

	public void setFloorNum(Long floorNum) {
		this.floorNum = floorNum;
	}

	@Column(name = "PRO_STATUS", insertable = false)
	public Integer getProStatus() {
		return this.proStatus;
	}

	public void setProStatus(Integer proStatus) {
		this.proStatus = proStatus;
	}

	@Column(name = "CREATOR", length = 20, updatable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19, updatable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MEMBER_ID")
	public MemberInfo getMember() {
		return member;
	}

	public void setMember(MemberInfo member) {
		this.member = member;
	}

}
