package com.work.domain;

// Generated 2014-8-27 20:58:29 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TReportInfo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_COMPLAINT_INFO")
public class ComplaintInfo implements java.io.Serializable {

	private String reportId;
	private String userIp;
	private String memberId;
	private String title;
	private String content;
	private String contactInfo;
	private Integer infoType;
	private String reportType;
	private Integer proStatus;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;
	private String infoId;

	public ComplaintInfo() {
	}

	public ComplaintInfo(String reportId) {
		this.reportId = reportId;
	}

	public ComplaintInfo(String reportId, String userIp, String memberId, String content, String contactInfo,
			Integer infoType, String reportType, String creator, Date createDate, String modifier, Date modifyDate) {
		this.reportId = reportId;
		this.userIp = userIp;
		this.memberId = memberId;
		this.content = content;
		this.contactInfo = contactInfo;
		this.infoType = infoType;
		this.reportType = reportType;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "REPORT_ID", unique = true, nullable = false, length = 32)
	public String getReportId() {
		return this.reportId;
	}

	public void setReportId(String reportId) {
		this.reportId = reportId;
	}

	@Column(name = "USER_IP", length = 32)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "MEMBER_ID", length = 32)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "CONTENT", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "CONTACT_INFO", length = 32)
	public String getContactInfo() {
		return this.contactInfo;
	}

	public void setContactInfo(String contactInfo) {
		this.contactInfo = contactInfo;
	}

	@Column(name = "INFO_TYPE")
	public Integer getInfoType() {
		return this.infoType;
	}

	public void setInfoType(Integer infoType) {
		this.infoType = infoType;
	}

	@Column(name = "REPORT_TYPE", length = 100)
	public String getReportType() {
		return this.reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}

	@Column(name = "CREATOR", length = 20, updatable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19, updatable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "PRO_STATUS", insertable = false)
	public Integer getProStatus() {
		return this.proStatus;
	}

	public void setProStatus(Integer proStatus) {
		this.proStatus = proStatus;
	}

	@Column(name = "INFO_ID", length = 32)
	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
}
