package com.work.domain;

// Generated 2014-8-19 22:47:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TParttimeCritique generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_CRITIQUE_INFO")
public class CritiqueInfo implements java.io.Serializable {

	private String critiqueId;
	private String userIp;
	private String memberId;
	private String infoId;
	private Integer type;
	private Integer infoType;
	private String title;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;
	private String cellphone;

	public CritiqueInfo() {
	}

	public CritiqueInfo(String critiqueId) {
		this.critiqueId = critiqueId;
	}

	public CritiqueInfo(String critiqueId, String userIp, String loginCode, String partTimeId, String content,
			String contactInfo, Integer type, String creator, Date createDate, String modifier, Date modifyDate) {
		this.critiqueId = critiqueId;
		this.userIp = userIp;
		this.type = type;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CRITIQUE_ID", unique = true, nullable = false, length = 32)
	public String getCritiqueId() {
		return this.critiqueId;
	}

	public void setCritiqueId(String critiqueId) {
		this.critiqueId = critiqueId;
	}

	@Column(name = "USER_IP", length = 32)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "TYPE")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "INFO_ID", length = 32)
	public String getInfoId() {
		return this.infoId;
	}

	public void setInfoId(String infoId) {
		this.infoId = infoId;
	}

	@Column(name = "INFO_TYPE")
	public Integer getInfoType() {
		return this.infoType;
	}

	public void setInfoType(Integer infoType) {
		this.infoType = infoType;
	}

	@Column(name = "TITLE", length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CREATOR", length = 20, updatable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19, updatable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "MEMBER_ID", length = 32)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "CELLPHONE", length = 16)
	public String getCellphone() {
		return cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

}
