package com.work.domain;

// Generated 2014-8-2 15:35:26 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TDataMiningSet generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_DATA_MINING_SET")
public class DataMiningSet implements java.io.Serializable {

	private String setId;
	private String url;
	private String netName;
	private String city;
	private String province;
	private PartTimeType partTimeType;
	private Integer pageNum;
	private Integer parseInterval;
	private String partTimeTypeName;
	private Integer miningStatus;

	public DataMiningSet() {
	}

	public DataMiningSet(String setId) {
		this.setId = setId;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "SET_ID", unique = true, nullable = false, length = 32)
	public String getSetId() {
		return this.setId;
	}

	public void setSetId(String setId) {
		this.setId = setId;
	}

	@Column(name = "URL", length = 1000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "NET_NAME", length = 50)
	public String getNetName() {
		return this.netName;
	}

	public void setNetName(String netName) {
		this.netName = netName;
	}

	@Column(name = "CITY", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "PROVINCE", length = 50)
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "PAGE_NUM")
	public Integer getPageNum() {
		return this.pageNum;
	}

	public void setPageNum(Integer pageNum) {
		this.pageNum = pageNum;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PART_TIME_TYPE_ID")
	public PartTimeType getPartTimeType() {
		return partTimeType;
	}

	public void setPartTimeType(PartTimeType partTimeType) {
		this.partTimeType = partTimeType;
	}

	@Column(name = "PART_TIME_TYPE_NAME")
	public String getPartTimeTypeName() {
		return partTimeTypeName;
	}

	@Column(name = "PARSE_INTERVAL")
	public Integer getParseInterval() {
		return parseInterval;
	}

	public void setParseInterval(Integer parseInterval) {
		this.parseInterval = parseInterval;
	}

	public void setPartTimeTypeName(String partTimeTypeName) {
		this.partTimeTypeName = partTimeTypeName;
	}

	@Column(name = "MINING_STATUS")
	public Integer getMiningStatus() {
		return miningStatus;
	}

	public void setMiningStatus(Integer miningStatus) {
		this.miningStatus = miningStatus;
	}

}
