package com.work.domain;

// Generated 2014-1-23 17:17:12 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TExpressDetail generated by hbm2java
 */
@Entity
@Table(name = "T_EXPRESS_DETAIL")
public class ExpressDetail implements java.io.Serializable {

	private static final long serialVersionUID = -7173269675966841710L;
	private String detailId;
	private String fieldKey;
	private String fieldName;
	private Float fieldLeft;
	private Float fieldTop;
	private Float height;
	private Float width;
	private Integer fieldShow;
	private String expressId;

	public ExpressDetail() {
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "DETAIL_ID", unique = true, nullable = false, length = 32)
	public String getDetailId() {
		return this.detailId;
	}

	public void setDetailId(String detailId) {
		this.detailId = detailId;
	}

	@Column(name = "FIELD_KEY", nullable = false, length = 50)
	public String getFieldKey() {
		return this.fieldKey;
	}

	public void setFieldKey(String fieldKey) {
		this.fieldKey = fieldKey;
	}

	@Column(name = "FIELD_NAME", length = 50)
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "HEIGHT", precision = 12, scale = 0)
	public Float getHeight() {
		return this.height;
	}

	@Column(name = "FIELD_LEFT", precision = 12, scale = 0)
	public Float getFieldLeft() {
		return fieldLeft;
	}

	public void setFieldLeft(Float fieldLeft) {
		this.fieldLeft = fieldLeft;
	}

	@Column(name = "FIELD_TOP", precision = 12, scale = 0)
	public Float getFieldTop() {
		return fieldTop;
	}

	public void setFieldTop(Float fieldTop) {
		this.fieldTop = fieldTop;
	}

	@Column(name = "FIELD_SHOW")
	public Integer getFieldShow() {
		return fieldShow;
	}

	public void setFieldShow(Integer fieldShow) {
		this.fieldShow = fieldShow;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	@Column(name = "WIDTH", precision = 12, scale = 0)
	public Float getWidth() {
		return this.width;
	}

	public void setWidth(Float width) {
		this.width = width;
	}

	@Column(name = "EXPRESS_ID", nullable = false, length = 32)
	public String getExpressId() {
		return this.expressId;
	}

	public void setExpressId(String expressId) {
		this.expressId = expressId;
	}

}
