package com.work.domain;

// Generated 2014-7-4 11:54:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TLotteryPrizeSet generated by hbm2java
 */
@Entity
@Table(name = "T_LOTTERY_PRIZE_SET")
public class LotteryPrizeSet implements java.io.Serializable {

	/**
	 * (域的意义,目的,功能)
	 */
	private static final long serialVersionUID = -8433930124657380530L;
	private String prizeId;
	private String prizeName;
	private int totalNum;
	private Integer usedNum;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;
	private Integer winAngle;
	private LotteryGift lotteryGift;
	private Lottery lottery;

	public LotteryPrizeSet() {
	}

	public LotteryPrizeSet(String prizeId, String prizeName, String lotteryId, int totalNum) {
		this.prizeId = prizeId;
		this.prizeName = prizeName;
		this.totalNum = totalNum;
	}

	public LotteryPrizeSet(String prizeId, String prizeName, String lotteryId, String lotteryGiftId, int totalNum,
			Integer usedNum, String creator, Date createDate, String modifier, Date modifyDate, Integer winAngle) {
		this.prizeId = prizeId;
		this.prizeName = prizeName;
		this.totalNum = totalNum;
		this.usedNum = usedNum;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
		this.winAngle = winAngle;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "PRIZE_ID", unique = true, nullable = false, length = 32)
	public String getPrizeId() {
		return this.prizeId;
	}

	public void setPrizeId(String prizeId) {
		this.prizeId = prizeId;
	}

	@Column(name = "PRIZE_NAME", nullable = false, length = 50)
	public String getPrizeName() {
		return this.prizeName;
	}

	public void setPrizeName(String prizeName) {
		this.prizeName = prizeName;
	}

	@Column(name = "TOTAL_NUM", nullable = false)
	public int getTotalNum() {
		return this.totalNum;
	}

	public void setTotalNum(int totalNum) {
		this.totalNum = totalNum;
	}

	@Column(name = "USED_NUM")
	public Integer getUsedNum() {
		return this.usedNum;
	}

	public void setUsedNum(Integer usedNum) {
		this.usedNum = usedNum;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "WIN_ANGLE")
	public Integer getWinAngle() {
		return this.winAngle;
	}

	public void setWinAngle(Integer winAngle) {
		this.winAngle = winAngle;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LOTTERY_GIFT_ID")
	public LotteryGift getLotteryGift() {
		return lotteryGift;
	}

	public void setLotteryGift(LotteryGift lotteryGift) {
		this.lotteryGift = lotteryGift;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LOTTERY_ID")
	public Lottery getLottery() {
		return lottery;
	}

	public void setLottery(Lottery lottery) {
		this.lottery = lottery;
	}

}
