package com.work.domain;

// Generated 2014-7-4 13:56:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TLotteryGift generated by hbm2java
 */
@Entity
@Table(name = "T_LOTTERY_GIFT")
public class LotteryGift implements java.io.Serializable {

	/**
	 * (域的意义,目的,功能)
	 */
	private static final long serialVersionUID = -1618356832879085390L;
	private String giftId;
	private String brandId;
	private String giftName;
	private Float marketPrice;
	private String giftUnit;
	private String picUrl;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;

	public LotteryGift() {
	}

	public LotteryGift(String giftId, String giftName) {
		this.giftId = giftId;
		this.giftName = giftName;
	}

	public LotteryGift(String giftId, String brandId, String giftName, Float marketPrice, String giftUnit,
			String picUrl, String creator, Date createDate, String modifier, Date modifyDate) {
		this.giftId = giftId;
		this.brandId = brandId;
		this.giftName = giftName;
		this.marketPrice = marketPrice;
		this.giftUnit = giftUnit;
		this.picUrl = picUrl;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "GIFT_ID", unique = true, nullable = false, length = 32)
	public String getGiftId() {
		return this.giftId;
	}

	public void setGiftId(String giftId) {
		this.giftId = giftId;
	}

	@Column(name = "BRAND_ID", length = 32)
	public String getBrandId() {
		return this.brandId;
	}

	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	@Column(name = "GIFT_NAME", nullable = false, length = 50)
	public String getGiftName() {
		return this.giftName;
	}

	public void setGiftName(String giftName) {
		this.giftName = giftName;
	}

	@Column(name = "MARKET_PRICE", precision = 12, scale = 0)
	public Float getMarketPrice() {
		return this.marketPrice;
	}

	public void setMarketPrice(Float marketPrice) {
		this.marketPrice = marketPrice;
	}

	@Column(name = "GIFT_UNIT", length = 10)
	public String getGiftUnit() {
		return this.giftUnit;
	}

	public void setGiftUnit(String giftUnit) {
		this.giftUnit = giftUnit;
	}

	@Column(name = "PIC_URL", length = 500)
	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
