package com.work.domain;

// Generated 2014-7-4 11:54:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * TLotteryProductSet generated by hbm2java
 */
@Entity
@Table(name = "T_LOTTERY_PRODUCT_SET", uniqueConstraints = @UniqueConstraint(columnNames = {
		"LOTTERY_ID", "PRODUCT_ID" }))
public class LotteryProductSet implements java.io.Serializable {

	/**
	 * (域的意义,目的,功能)
	 */
	private static final long serialVersionUID = 7696694897858219007L;
	private String productSetId;
	private String lotteryId;
	private String productId;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;

	public LotteryProductSet() {
	}

	public LotteryProductSet(String productSetId) {
		this.productSetId = productSetId;
	}

	public LotteryProductSet(String productSetId, String lotteryId, String productId, String creator, Date createDate,
			String modifier, Date modifyDate) {
		this.productSetId = productSetId;
		this.lotteryId = lotteryId;
		this.productId = productId;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "PRODUCT_SET_ID", unique = true, nullable = false, length = 32)
	public String getProductSetId() {
		return this.productSetId;
	}

	public void setProductSetId(String productSetId) {
		this.productSetId = productSetId;
	}

	@Column(name = "LOTTERY_ID", length = 32)
	public String getLotteryId() {
		return this.lotteryId;
	}

	public void setLotteryId(String lotteryId) {
		this.lotteryId = lotteryId;
	}

	@Column(name = "PRODUCT_ID", length = 32)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
