package com.work.domain;

// Generated 2014-7-4 11:54:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TLottery generated by hbm2java
 */
@Entity
@Table(name = "T_LOTTERY")
public class Lottery implements java.io.Serializable {

	/**
	 * (域的意义,目的,功能)
	 */
	private static final long serialVersionUID = -2406174265314560806L;
	private String lotteryId;
	private String brandId;
	private String lotteryName;
	private String lotteryDesc;
	private Date beginTime;
	private Date endTime;
	private Integer lotteryNumber;
	private Integer continueLottery;
	private Integer winningRate;
	private String notWinInfo;
	private String notWinAngle;
	private String lotteryPic;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;
	private Integer status;

	public Lottery() {
	}

	public Lottery(String lotteryId) {
		this.lotteryId = lotteryId;
	}

	public Lottery(String lotteryId, String brandId, String lotteryName, String lotteryDesc, Date beginTime,
			Date endTime, Integer lotteryNumber, Integer continueLottery, Integer winningRate, String notWinInfo,
			String notWinAngle, String lotteryPic, String creator, Date createDate, String modifier, Date modifyDate,
			Integer status) {
		this.lotteryId = lotteryId;
		this.brandId = brandId;
		this.lotteryName = lotteryName;
		this.lotteryDesc = lotteryDesc;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.lotteryNumber = lotteryNumber;
		this.continueLottery = continueLottery;
		this.winningRate = winningRate;
		this.notWinInfo = notWinInfo;
		this.notWinAngle = notWinAngle;
		this.lotteryPic = lotteryPic;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
		this.status = status;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "LOTTERY_ID", unique = true, nullable = false, length = 32)
	public String getLotteryId() {
		return this.lotteryId;
	}

	public void setLotteryId(String lotteryId) {
		this.lotteryId = lotteryId;
	}

	@Column(name = "BRAND_ID", length = 32)
	public String getBrandId() {
		return this.brandId;
	}

	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	@Column(name = "LOTTERY_NAME", length = 32)
	public String getLotteryName() {
		return this.lotteryName;
	}

	public void setLotteryName(String lotteryName) {
		this.lotteryName = lotteryName;
	}

	@Column(name = "LOTTERY_DESC", length = 65535)
	public String getLotteryDesc() {
		return this.lotteryDesc;
	}

	public void setLotteryDesc(String lotteryDesc) {
		this.lotteryDesc = lotteryDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BEGIN_TIME", length = 19)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_TIME", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "LOTTERY_NUMBER")
	public Integer getLotteryNumber() {
		return this.lotteryNumber;
	}

	public void setLotteryNumber(Integer lotteryNumber) {
		this.lotteryNumber = lotteryNumber;
	}

	@Column(name = "CONTINUE_LOTTERY")
	public Integer getContinueLottery() {
		return this.continueLottery;
	}

	public void setContinueLottery(Integer continueLottery) {
		this.continueLottery = continueLottery;
	}

	@Column(name = "WINNING_RATE")
	public Integer getWinningRate() {
		return this.winningRate;
	}

	public void setWinningRate(Integer winningRate) {
		this.winningRate = winningRate;
	}

	@Column(name = "NOT_WIN_INFO", length = 50)
	public String getNotWinInfo() {
		return this.notWinInfo;
	}

	public void setNotWinInfo(String notWinInfo) {
		this.notWinInfo = notWinInfo;
	}

	@Column(name = "NOT_WIN_ANGLE", length = 50)
	public String getNotWinAngle() {
		return this.notWinAngle;
	}

	public void setNotWinAngle(String notWinAngle) {
		this.notWinAngle = notWinAngle;
	}

	@Column(name = "LOTTERY_PIC", length = 500)
	public String getLotteryPic() {
		return this.lotteryPic;
	}

	public void setLotteryPic(String lotteryPic) {
		this.lotteryPic = lotteryPic;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "STATUS")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
