package com.work.domain;

// Generated 2014-8-24 15:47:17 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TMemAddressList generated by hbm2java
 */
@Entity
@Table(name = "T_MEM_ADDRESS_LIST")
public class MemAddressList implements java.io.Serializable {

	/**
	 * (域的意义,目的,功能)
	 */
	private static final long serialVersionUID = -7325274806367708806L;
	private String listId;
	private String memberId;
	private String contacts;
	private String contactPhone;
	private String noteName;
	private String remarks;
	private Integer starTarget;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;
	private String provinceName;
	private String cityName;

	public MemAddressList() {
	}

	public MemAddressList(String listId) {
		this.listId = listId;
	}

	public MemAddressList(String listId, String memberId, String contacts, String contactPhone, String noteName,
			String remarks, Integer starTarget, String creator, Date createDate, String modifier, Date modifyDate) {
		this.listId = listId;
		this.memberId = memberId;
		this.contacts = contacts;
		this.contactPhone = contactPhone;
		this.noteName = noteName;
		this.remarks = remarks;
		this.starTarget = starTarget;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "LIST_ID", unique = true, nullable = false, length = 32)
	public String getListId() {
		return this.listId;
	}

	public void setListId(String listId) {
		this.listId = listId;
	}

	@Column(name = "MEMBER_ID", length = 32)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "CONTACTS", length = 50)
	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	@Column(name = "CONTACT_PHONE", length = 20)
	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	@Column(name = "NOTE_NAME", length = 50)
	public String getNoteName() {
		return this.noteName;
	}

	public void setNoteName(String noteName) {
		this.noteName = noteName;
	}

	@Column(name = "REMARKS", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "STAR_TARGET", insertable = false)
	public Integer getStarTarget() {
		return this.starTarget;
	}

	public void setStarTarget(Integer starTarget) {
		this.starTarget = starTarget;
	}

	@Column(name = "CREATOR", length = 20, updatable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19, updatable = false)
	public Date getCreateDate() {
		return this.createDate;
	}
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}
	@Column(name = "PROVINCE_NAME", length = 500)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "CITY_NAME", length = 500)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

}
