package com.work.domain;

// Generated 2014-8-16 16:32:52 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
 * MemberInfo generated by hbm2java
 */
@Entity
@Table(name = "T_MEMBER_INFO")
public class MemberInfo implements java.io.Serializable {

	private static final long serialVersionUID = 2545853818221388482L;

	private String memberId;
	private String loginCode;
	private String password;
	private Date passwordUpdateTime;
	private Integer loginType;
	private Date lastLoginTime;
	private String loginIp;
	private Integer status;
	private String memberName;
	private String realName;
	private String emailAddress;
	private String cellphone;
	private Integer gender;
	private Date birthday;
	private String imagePath;
	private String province;
	private String city;
	private String region;
	private Integer hasHealthCard;
	private String freeTime;
	private String university;
	private Integer height;
	private Integer weight;
	private Integer totalScore;
	private Integer totalScore2;
	private Integer remainScore;
	private Integer remainScore2;
	private Date createTime;
	private String createTime1;
	private String createTime2;
	private String qq;
	private String wechat;
	private Integer birthdayMonth;
	private Integer birthdayMonth2;

	public MemberInfo() {
	}

	public MemberInfo(String memberId) {
		this.memberId = memberId;
	}

	public MemberInfo(String memberId, String loginCode, String password, int status, String memberName,
			int totalScore, int remainScore) {
		this.memberId = memberId;
		this.loginCode = loginCode;
		this.password = password;
		this.status = status;
		this.memberName = memberName;
		this.totalScore = totalScore;
		this.remainScore = remainScore;
	}

	public MemberInfo(String memberId, String loginCode, String password, Date passwordUpdateTime, Integer loginType,
			Date lastLoginTime, String loginIp, int status, String memberName, String realName, String emailAddress,
			String cellphone, Integer gender, Date birthday, String imagePath, String province, String city,
			String region, Integer hasHealthCard, String freeTime, String university, Integer height, Integer weight,
			int totalScore, int remainScore, Date createTime, String qq, String wechat) {
		this.memberId = memberId;
		this.loginCode = loginCode;
		this.password = password;
		this.passwordUpdateTime = passwordUpdateTime;
		this.loginType = loginType;
		this.lastLoginTime = lastLoginTime;
		this.loginIp = loginIp;
		this.status = status;
		this.memberName = memberName;
		this.realName = realName;
		this.emailAddress = emailAddress;
		this.cellphone = cellphone;
		this.gender = gender;
		this.birthday = birthday;
		this.imagePath = imagePath;
		this.province = province;
		this.city = city;
		this.region = region;
		this.hasHealthCard = hasHealthCard;
		this.freeTime = freeTime;
		this.university = university;
		this.height = height;
		this.weight = weight;
		this.totalScore = totalScore;
		this.remainScore = remainScore;
		this.createTime = createTime;
		this.qq = qq;
		this.wechat = wechat;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "MEMBER_ID", unique = true, nullable = false, length = 32)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "LOGIN_CODE", nullable = false, length = 32)
	public String getLoginCode() {
		return this.loginCode;
	}

	public void setLoginCode(String loginCode) {
		this.loginCode = loginCode;
	}

	@Column(name = "PASSWORD", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PASSWORD_UPDATE_TIME", length = 19)
	public Date getPasswordUpdateTime() {
		return this.passwordUpdateTime;
	}

	public void setPasswordUpdateTime(Date passwordUpdateTime) {
		this.passwordUpdateTime = passwordUpdateTime;
	}

	@Column(name = "LOGIN_TYPE")
	public Integer getLoginType() {
		return this.loginType;
	}

	public void setLoginType(Integer loginType) {
		this.loginType = loginType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN_TIME", length = 19)
	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	@Column(name = "LOGIN_IP", length = 50)
	public String getLoginIp() {
		return this.loginIp;
	}

	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	@Column(name = "STATUS", nullable = false)
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "MEMBER_NAME", nullable = false, length = 50)
	public String getMemberName() {
		return this.memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	@Column(name = "REAL_NAME", length = 50)
	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	@Column(name = "EMAIL_ADDRESS", length = 100)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "CELLPHONE", length = 16)
	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	@Column(name = "GENDER")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BIRTHDAY", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "IMAGE_PATH", length = 150)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "PROVINCE", length = 32)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "CITY", length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "REGION", length = 32)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "HAS_HEALTH_CARD")
	public Integer getHasHealthCard() {
		return this.hasHealthCard;
	}

	public void setHasHealthCard(Integer hasHealthCard) {
		this.hasHealthCard = hasHealthCard;
	}

	@Column(name = "FREE_TIME", length = 200)
	public String getFreeTime() {
		return this.freeTime;
	}

	public void setFreeTime(String freeTime) {
		this.freeTime = freeTime;
	}

	@Column(name = "UNIVERSITY", length = 50)
	public String getUniversity() {
		return this.university;
	}

	public void setUniversity(String university) {
		this.university = university;
	}

	@Column(name = "HEIGHT")
	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	@Column(name = "WEIGHT")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	@Column(name = "TOTAL_SCORE", nullable = false, insertable = false)
	public Integer getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(Integer totalScore) {
		this.totalScore = totalScore;
	}

	@Column(name = "REMAIN_SCORE", nullable = false, insertable = false)
	public Integer getRemainScore() {
		return this.remainScore;
	}

	public void setRemainScore(Integer remainScore) {
		this.remainScore = remainScore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 19, updatable = false)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "QQ", length = 32)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "WECHAT", length = 64)
	public String getWechat() {
		return this.wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	@Transient
	public Integer getTotalScore2() {
		return totalScore2;
	}

	public void setTotalScore2(Integer totalScore2) {
		this.totalScore2 = totalScore2;
	}

	@Transient
	public Integer getRemainScore2() {
		return remainScore2;
	}

	public void setRemainScore2(Integer remainScore2) {
		this.remainScore2 = remainScore2;
	}
	
	@Transient
	public String getCreateTime1() {
		return createTime1;
	}
	
	public void setCreateTime1(String createTime1) {
		this.createTime1 = createTime1;
	}

	@Transient
	public String getCreateTime2() {
		return createTime2;
	}

	public void setCreateTime2(String createTime2) {
		this.createTime2 = createTime2;
	}

	@Transient
	public Integer getBirthdayMonth() {
		return birthdayMonth;
	}

	public void setBirthdayMonth(Integer birthdayMonth) {
		this.birthdayMonth = birthdayMonth;
	}

	@Transient
	public Integer getBirthdayMonth2() {
		return birthdayMonth2;
	}

	public void setBirthdayMonth2(Integer birthdayMonth2) {
		this.birthdayMonth2 = birthdayMonth2;
	}
}
