package com.work.domain;

// Generated 2014-7-25 20:48:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TPartTimeInfo generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_PART_TIME_ENGINE")
public class PartTimeEngine implements java.io.Serializable {

	private String partTimeId;
	private String partTimeTitle;
	private String partTimeContent;
	private PartTimeType partTimeType;
	private String source;
	private String sourceUrl;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;
	private String cellPhone;
	private String contacts;
	private String address;
	private String salary;
	private String provinceName;
	private String cityName;
	private String areaName;
	private Date beginTime;
	private Date endTime;
	private String workTime;
	private Integer genderReq;
	private String recruitmentNumber;
	private Integer isVerify;
	private String partTimeTypeName;

	private Integer isExist;

	public PartTimeEngine() {
	}

	public PartTimeEngine(String partTimeId) {
		this.partTimeId = partTimeId;
	}

	public PartTimeEngine(String partTimeId, String partTimeTitle, String partTimeContent, String partTimeType,
			String source, String sourceUrl, String creator, Date createDate, String modifier, Date modifyDate,
			String cellPhone, String contacts, String address, String salary, String provinceName, String cityName,
			String areaName, Date beginTime, Date endTime, String workTime, Integer genderReq,
			String recruitmentNumber, Integer stickStatus) {
		this.partTimeId = partTimeId;
		this.partTimeTitle = partTimeTitle;
		this.partTimeContent = partTimeContent;
		this.source = source;
		this.sourceUrl = sourceUrl;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
		this.cellPhone = cellPhone;
		this.contacts = contacts;
		this.address = address;
		this.salary = salary;
		this.provinceName = provinceName;
		this.cityName = cityName;
		this.areaName = areaName;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.workTime = workTime;
		this.genderReq = genderReq;
		this.recruitmentNumber = recruitmentNumber;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "PART_TIME_ID", unique = true, nullable = false, length = 32)
	public String getPartTimeId() {
		return this.partTimeId;
	}

	public void setPartTimeId(String partTimeId) {
		this.partTimeId = partTimeId;
	}

	@Column(name = "PART_TIME_TITLE", length = 500)
	public String getPartTimeTitle() {
		return this.partTimeTitle;
	}

	public void setPartTimeTitle(String partTimeTitle) {
		this.partTimeTitle = partTimeTitle;
	}

	@Column(name = "PART_TIME_CONTENT", length = 65535)
	public String getPartTimeContent() {
		return this.partTimeContent;
	}

	public void setPartTimeContent(String partTimeContent) {
		this.partTimeContent = partTimeContent;
	}

	@Column(name = "SOURCE", length = 100)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "SOURCE_URL", length = 1000)
	public String getSourceUrl() {
		return this.sourceUrl;
	}

	public void setSourceUrl(String sourceUrl) {
		this.sourceUrl = sourceUrl;
	}

	@Column(name = "CREATOR", length = 20, updatable = false)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19, updatable = false)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "CELL_PHONE", length = 11)
	public String getCellPhone() {
		return this.cellPhone;
	}

	public void setCellPhone(String cellPhone) {
		this.cellPhone = cellPhone;
	}

	@Column(name = "CONTACTS", length = 20)
	public String getContacts() {
		return this.contacts;
	}

	public void setContacts(String contacts) {
		this.contacts = contacts;
	}

	@Column(name = "ADDRESS", length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "SALARY", length = 100)
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Column(name = "PROVINCE_NAME", length = 500)
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "CITY_NAME", length = 500)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "AREA_NAME", length = 500)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BEGIN_TIME", length = 19)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_TIME", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "WORK_TIME", length = 500)
	public String getWorkTime() {
		return this.workTime;
	}

	public void setWorkTime(String workTime) {
		this.workTime = workTime;
	}

	@Column(name = "GENDER_REQ")
	public Integer getGenderReq() {
		return this.genderReq;
	}

	public void setGenderReq(Integer genderReq) {
		this.genderReq = genderReq;
	}

	@Column(name = "RECRUITMENT_NUMBER", length = 100)
	public String getRecruitmentNumber() {
		return this.recruitmentNumber;
	}

	public void setRecruitmentNumber(String recruitmentNumber) {
		this.recruitmentNumber = recruitmentNumber;
	}

	@Column(name = "IS_VERIFY")
	public Integer getIsVerify() {
		return isVerify;
	}

	public void setIsVerify(Integer isVerify) {
		this.isVerify = isVerify;
	}

	@Column(name = "IS_EXIST")
	public Integer getIsExist() {
		return isExist;
	}

	public void setIsExist(Integer isExist) {
		this.isExist = isExist;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PART_TIME_TYPE_ID")
	public PartTimeType getPartTimeType() {
		return partTimeType;
	}

	public void setPartTimeType(PartTimeType partTimeType) {
		this.partTimeType = partTimeType;
	}

	@Column(name = "PART_TIME_TYPE_NAME", length = 20)
	public String getPartTimeTypeName() {
		return partTimeTypeName;
	}

	public void setPartTimeTypeName(String partTimeTypeName) {
		this.partTimeTypeName = partTimeTypeName;
	}

}
