package com.work.domain;

// Generated 2014-10-9 23:28:03 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * ScoreSetting generated by hbm2java
 */
@Entity
@Table(name = "T_SCORE_SETTING")
public class ScoreSetting implements java.io.Serializable {
	
	private static final long serialVersionUID = 599385790155881102L;
	
	private String id;
	private String target;
	private int score;
	private String description;
	private String modifier;
	private Date modifyDate;

	public ScoreSetting() {
	}

	public ScoreSetting(String id, String target, int score) {
		this.id = id;
		this.target = target;
		this.score = score;
	}

	public ScoreSetting(String id, String target, int score,
			String description, String modifier, Date modifyDate) {
		this.id = id;
		this.target = target;
		this.score = score;
		this.description = description;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "TARGET", nullable = false, length = 100)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "SCORE", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
