package com.work.domain;

//Generated 2014-10-9 23:00:32 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

/**
* ScoreDetail generated by hbm2java
*/
@Entity
@Table(name = "T_SCORE_DETAIL")
public class ScoreDetail implements java.io.Serializable {

	private static final long serialVersionUID = -8284177288667335676L;
	
	private String id;
	private String memberId;
	private int score;
	private String detail;
	private Date createTime;
	private String operateType;
	private String target;
	private String object; //目标
	private MemberInfo subjectInfo; //操作人会员信息
	private MemberInfo objectInfo; //目标会员信息（用于推荐有礼）
	private MemberResume objectResume; //目标会员简历（用于推荐有礼）
	private Boolean objectCompleteResume;//目标会员是否有完善简历（用于推荐有礼）

	public ScoreDetail() {
	}
	
	public ScoreDetail(String memberId) {
		this.memberId = memberId;
	}

	public ScoreDetail(String id, String memberId, int score, Date createTime) {
		this.id = id;
		this.memberId = memberId;
		this.score = score;
		this.createTime = createTime;
	}

	public ScoreDetail(String id, String memberId, int score, String detail,
			Date createTime, String operateType, String target) {
		this.id = id;
		this.memberId = memberId;
		this.score = score;
		this.detail = detail;
		this.createTime = createTime;
		this.operateType = operateType;
		this.target = target;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "MEMBER_ID", nullable = false, length = 32)
	public String getMemberId() {
		return this.memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	@Column(name = "SCORE", nullable = false)
	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	@Column(name = "DETAIL", length = 100)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "OPERATE_TYPE", length = 50)
	public String getOperateType() {
		return this.operateType;
	}

	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}

	@Column(name = "TARGET", length = 100)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "OBJECT", length = 50)
	public String getObject() {
		return object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	@Transient
	public MemberInfo getSubjectInfo() {
		return subjectInfo;
	}

	public void setSubjectInfo(MemberInfo subjectInfo) {
		this.subjectInfo = subjectInfo;
	}

	@Transient
	public MemberInfo getObjectInfo() {
		return objectInfo;
	}

	public void setObjectInfo(MemberInfo objectInfo) {
		this.objectInfo = objectInfo;
	}

	@Transient
	public MemberResume getObjectResume() {
		return objectResume;
	}

	public void setObjectResume(MemberResume objectResume) {
		this.objectResume = objectResume;
	}

	@Transient
	public Boolean getObjectCompleteResume() {
		return objectCompleteResume;
	}

	public void setObjectCompleteResume(Boolean objectCompleteResume) {
		this.objectCompleteResume = objectCompleteResume;
	}
}