package com.work.domain;

// Generated 2014-2-21 13:53:19 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TSenderInfo generated by hbm2java
 */
@Entity
@Table(name = "T_SENDER_INFO")
public class SenderInfo implements java.io.Serializable {

	/**
	 * (域的意义,目的,功能)
	 */
	private static final long serialVersionUID = 5952361470044572711L;
	private String senderId;
	private String province;
	private String city;
	private String region;
	private String senderAddress;
	private String senderCompanyname;
	private String senderName;
	private String sendeRpostcode;
	private String senderTel;
	private Integer defaultSet;

	public SenderInfo() {
	}

	public SenderInfo(String senderId) {
		this.senderId = senderId;
	}

	public SenderInfo(String senderId, String province, String city, String region, String senderAddress,
			String senderCompanyname, String senderName, String sendeRpostcode, String senderTel, Integer defaultSet) {
		this.senderId = senderId;
		this.province = province;
		this.city = city;
		this.region = region;
		this.senderAddress = senderAddress;
		this.senderCompanyname = senderCompanyname;
		this.senderName = senderName;
		this.sendeRpostcode = sendeRpostcode;
		this.senderTel = senderTel;
		this.defaultSet = defaultSet;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "SENDER_ID", unique = true, nullable = false, length = 32)
	public String getSenderId() {
		return this.senderId;
	}

	public void setSenderId(String senderId) {
		this.senderId = senderId;
	}

	@Column(name = "PROVINCE", length = 50)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "CITY", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "REGION", length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "SENDER_ADDRESS", length = 150)
	public String getSenderAddress() {
		return this.senderAddress;
	}

	public void setSenderAddress(String senderAddress) {
		this.senderAddress = senderAddress;
	}

	@Column(name = "SENDER_COMPANYNAME", length = 150)
	public String getSenderCompanyname() {
		return this.senderCompanyname;
	}

	public void setSenderCompanyname(String senderCompanyname) {
		this.senderCompanyname = senderCompanyname;
	}

	@Column(name = "SENDER_NAME", length = 50)
	public String getSenderName() {
		return this.senderName;
	}

	public void setSenderName(String senderName) {
		this.senderName = senderName;
	}

	@Column(name = "SENDE_RPOSTCODE", length = 10)
	public String getSendeRpostcode() {
		return this.sendeRpostcode;
	}

	public void setSendeRpostcode(String sendeRpostcode) {
		this.sendeRpostcode = sendeRpostcode;
	}

	@Column(name = "SENDER_TEL", length = 20)
	public String getSenderTel() {
		return this.senderTel;
	}

	public void setSenderTel(String senderTel) {
		this.senderTel = senderTel;
	}

	@Column(name = "DEFAULT_SET")
	public Integer getDefaultSet() {
		return this.defaultSet;
	}

	public void setDefaultSet(Integer defaultSet) {
		this.defaultSet = defaultSet;
	}

}
