package com.work.domain;

// Generated 2014-7-28 11:41:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TSmsConfig generated by hbm2java
 * 短信接口配置类
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "T_SMS_CONFIG")
public class SmsConfig implements java.io.Serializable {

	private String smsConfigId;
	private String smsParamName;
	private String smsParamValue;
	private String smsParamTag;
	private String smsParamDesc;
	private String creator;
	private Date createDate;
	private String modifier;
	private Date modifyDate;

	public SmsConfig() {
	}

	public SmsConfig(String smsConfigId) {
		this.smsConfigId = smsConfigId;
	}

	public SmsConfig(String smsConfigId, String smsParamName, String smsParamValue, String smsParamTag, String creator,
			Date createDate, String modifier, Date modifyDate) {
		this.smsConfigId = smsConfigId;
		this.smsParamName = smsParamName;
		this.smsParamValue = smsParamValue;
		this.smsParamTag = smsParamTag;
		this.creator = creator;
		this.createDate = createDate;
		this.modifier = modifier;
		this.modifyDate = modifyDate;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "SMS_CONFIG_ID", unique = true, nullable = false, length = 32)
	public String getSmsConfigId() {
		return this.smsConfigId;
	}

	public void setSmsConfigId(String smsConfigId) {
		this.smsConfigId = smsConfigId;
	}

	@Column(name = "SMS_PARAM_NAME", length = 32)
	public String getSmsParamName() {
		return this.smsParamName;
	}

	public void setSmsParamName(String smsParamName) {
		this.smsParamName = smsParamName;
	}

	@Column(name = "SMS_PARAM_VALUE", length = 1000)
	public String getSmsParamValue() {
		return this.smsParamValue;
	}

	public void setSmsParamValue(String smsParamValue) {
		this.smsParamValue = smsParamValue;
	}

	@Column(name = "SMS_PARAM_TAG", length = 32)
	public String getSmsParamTag() {
		return this.smsParamTag;
	}

	public void setSmsParamTag(String smsParamTag) {
		this.smsParamTag = smsParamTag;
	}

	@Column(name = "SMS_PARAM_DESC", length = 32)
	public String getSmsParamDesc() {
		return smsParamDesc;
	}

	public void setSmsParamDesc(String smsParamDesc) {
		this.smsParamDesc = smsParamDesc;
	}

	@Column(name = "CREATOR", length = 20)
	public String getCreator() {
		return this.creator;
	}

	public void setCreator(String creator) {
		this.creator = creator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "MODIFIER", length = 20)
	public String getModifier() {
		return this.modifier;
	}

	public void setModifier(String modifier) {
		this.modifier = modifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

}
